version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    volumes:
      - ./uploaded_evidence:/app/uploaded_evidence
      - ./generated_reports:/app/generated_reports
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
